---
- name: Add an Apt signing key for cloudfoundry
  apt_key:
    url: https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key
    state: present

- apt_repository:
    repo: deb http://packages.cloudfoundry.org/debian stable main
    state: present
    filename: 'cloudfoundry-cli'
